config/routes.rb
Rails.application.routes.draw do
  resources :bproces, only: :autocomlete do
    get :autocomplete, on: :collection
  end
  resources :iresources, only: :autocomlete do
    get :autocomplete, on: :collection
  end
  resources :users, only: :autocomlete do
    get :autocomplete, on: :collection
  end
  resources :activities
  resources :agents do
    get :autocomplete, on: :collection
    member do
      get :new_contract # новый договор контрагента
    end
  end
  resources :bapps do
    get :autocomplete, on: :collection
  end
  resources :bproce_bapps, only: [:create, :destroy, :show, :edit, :update]
  resources :bproce_business_roles, only: [:show]
  resources :bproce_iresources, only: [:new, :create, :destroy, :show, :edit, :update]
  resources :bproce_workplaces, only: [:create, :destroy, :show]
  resources :bproce_contracts, except: :index
  resources :bproce_documents, except: :index
  resources :bproces, except: :new do
    resources :bapps
    resources :business_roles, only: [:new]
    resources :documents, only: [:new, :index]
    resources :contracts, only: [:index]
    collection do
      get :manage
      post :rebuild
      get :list
    end
    member do
      get :order  # распоряжение о назначении исполнителей в процесс
      get :doc    # описание процесса
      get :card   # карточка процесса
      get :check_list # чек-лист карточки процесса
      get :check_list_improve # чеклист улучшения процесса
      get :metrics # метрики процесса
      get :new_metric # добавить новую метрику в процесс
      get :new_document, to: 'documents#new'
      get :new_sub_process # добавить подпроцесс
    end
  end
  resources :business_roles do
    member do
      get :create_user # назначить исполнителя
      post :update_user
      get :mail # отправить всем исполнителям письмо
      post :mail_all
    end
  end
  resources :contracts do
    get :autocomplete, on: :collection
    member do
      get :approval_sheet # Лист согласования
      get :scan_create
      get :scan_delete
      post :update_scan
      get :bproce_create
      get :clone # создать похожий договор
    end
  end
  resources :contract_scans, only: [:destroy, :edit, :update]
  resources :directives do
    resources :documents  # документы на основании директивы
    get :autocomplete, on: :collection
    member do
      get :document_create
      post :document_update
    end
  end
  resources :documents do
    get :autocomplete, on: :collection
    member do
      get :file_create
      get :file_delete
      patch :update_file
      get :approval_sheet # Лист согласования
      get :clone # создать карточку похожего документа
      get :add_favorite     # добровольное занесение в избранное
      get :add_to_favorite  # юрист заносит в обязательные
      post :update_favorite
      get :show_files
      get :bproce_create
    end
  end
  resources :document_directives
  resources :iresources

  resources :home, only: [:index] do
    member do
      get :create_letter    # создать официальное письмо
      get :create_memo      # создать служебную записку
      get :create_vacation  # создать заявление на отпуск
    end
  end

  resources :letters do     # письма, корреспонденция
    collection do
      get :senders
      get :log_week    # журнал регистрации за неделю
      get :check       # контроль
    end
    member do
      get :appendix_create
      get :appendix_delete
      post :appendix_update
      get :clone            # письмо от того же корреспондента
      get :create_outgoing  # исходящее письмо на входящее
      get :create_requirement # создать требование
      get :create_task
      get :create_user # назначить исполнителя
      post :update_user
      get :register       # зарегистрировать
      get :reestr         # реестр выписок
    end
  end
  resources :letter_appendixes, only: [:destroy, :edit, :update]

  resources :metrics do
    member do
      get :values
      get :new_value
      get :set
      get :test
      get :set_values
    end
  end
  resources :metric_values, only: [:edit, :update, :new, :create, :destroy]
  get 'bproces/tags/:tag', to: 'bproces#index', as: :tag_bproces
  get 'bapps/tags/:tag', to: 'bapps#index', as: :tag_bapps
  get 'documents/tags/:tag', to: 'documents#index', as: :tag_documents
  # get 'tags/:tag', to: 'bproces#index', as: :tag
  # get 'tags', to: 'bproces#index'

  resources :tasks do
    collection do
      get :check       # контроль
    end
    member do
      get :create_user      # назначить исполнителя
      post :update_user
      get :report
    end
  end
  resources :terms
  resources :requirements do
    member do
      get :create_task
      get :create_user      # назначить исполнителя
      post :update_user
      get :tasks_list
      get :tasks_report
    end
  end
  resources :roles, only: [:index, :show]

  devise_for :users
  devise_scope :users do
    get 'sign_in',  to: 'devise/sessions#new'
    get 'sign_out', to: 'devise/sessions#destroy'
    get 'sign_up',  to: 'devise/registrations#new'
  end
  resources :users, only: [:index, :show, :edit, :update] do
    member do
      get :order # распоряжение о назначении исполнителя на роли в процессах
      get :pass # пропуск
      get :uworkplaces
      get :uroles
      get :documents
      get :contracts
      get :contracts_pay
      get :resources
      get :processes
      get :execute # К исполнению (письма, задачи, требования).
      get :avatar_create
      get :avatar_delete
      patch :update_avatar
      get :move_to    # назначить другого пользователя всех бизнес-ролей сотрудника
      post :business_roles_move_to  # перенести бизнес-роли новому пользователю
      get :stop_all # прератить исполнение всех ролей сотрудником
    end
    resources :roles, only: [:create, :destroy]
  end
  resources :user_business_roles, only: [:new, :create, :destroy, :edit, :update, :show]
  resources :user_documents, only: [:destroy]
  resources :user_letters, only: [:destroy, :update, :create, :show]
  resources :user_requirements, only: [:destroy, :update, :create, :show]
  resources :user_tasks, only: [:destroy, :update, :create, :show]
  resources :user_workplaces

  # match '/bproceses' => 'bproces#list', :via => :get  # получение полного списка процессов
  match '/bprocess' => 'bproces#manage', :via => :get # получение полного списка процессов
  # match '/bproces/:id/card' => 'bproces#card', :via => :get  # карточка процесса
  # match '/bproces/:id/doc' => 'bproces#doc', :via => :get  # заготовка описания процесса
  match '/workplaces/switch' => 'workplaces#switch', :via => :get # подключения рабочих мест
  resources :workplaces do
    get :autocomplete, on: :collection
    member do
      get :create_user # назначить исполнителя
      post :update_user
    end
  end

  match '/about' => 'pages#about', via: :get
  get 'pages/about'
  root to: 'home#index'
end

app/controllers/documents_controller.rb
# frozen_string_literal: true

class DocumentsController < ApplicationController
  respond_to :odt, only: :index
  respond_to :pdf, only: :show
  respond_to :html
  respond_to :xml, :json, only: %i[index show]
  helper_method :sort_column, :sort_direction
  before_action :authenticate_user!, only: %i[edit new]
  before_action :get_document, except: %i[index print view create new]

  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  def index
    @title_doc = 'Список документов'
    if params[:directive_id].present? # документы относящиеся к директиве
      @directive = Directive.find(params[:directive_id])
      @documents = @directive.document.paginate(per_page: 100, page: params[:page])
    elsif params[:bproce_id].present?
      @title_doc = ''
      @bproce = Bproce.find(params[:bproce_id])
      ids = BproceDocument.where(bproce_id: @bproce.id).pluck(:document_id)
      @documents = Document.where(id: ids).all
      if params[:status].present? #  список документов, имеющих конкретный статус
        @documents = @documents.where(status: params[:status])
        @title_doc = " в статусе [#{params[:status]}]"
      end
      @documents = @documents.paginate(per_page: 100, page: params[:page])
    else
      @documents = Document.all
      if params[:all].present?
        @documents = @documents.order('cast (part as integer)', :name).all
        @title_doc = 'Каталог документов'
      else
        if params[:place].present? # список документов по месту хранения
          if params[:place].empty?
            @documents = @documents.where("place = ''")
            @title_doc += ' - место хранения оригинала [не указано]'
          else
            @documents = @documents.where(place: params[:place])
            @title_doc += ", хранящихся в [#{params[:place]}]: #{DOCUMENT_PLACE.key(params[:place])}"
          end
        else
          if params[:dlevel].present? #  список документов уровня
            @documents = @documents.where(dlevel: params[:dlevel])
            @title_doc += " уровень [#{params[:dlevel]}]: #{DOCUMENT_LEVEL.key(params[:dlevel].to_i)}"
          else
            if params[:part].present? #  список документов раздела документооборота
              @documents = @documents.where(part: params[:part])
              @title_doc += " раздела [#{params[:part]}]"
            else
              if params[:user].present? #  список документов пользователя
                @user = User.find(params[:user])
                @documents = Document.where(owner_id: params[:user])
                @title_doc += ', ответственный [' + @user.displayname + ']' if @user
              else
                if params[:tag].present?
                  @title_doc += ", тэг [#{params[:tag]}]"
                  @documents = @documents.tagged_with(params[:tag]).search(params[:search])
                end
                if params[:search].present?
                  @title_doc += ", содержащих [#{params[:search]}]"
                  @documents = @documents.full_search(params[:search])
                end
                if params[:status].present? #  список документов, имеющих конкретный статус
                  @documents = @documents.where(status: params[:status])
                  @title_doc += " в статусе [#{params[:status]}]"
                end
              end
            end
          end
        end
      end
    end
    respond_to do |format|
      format.html do
        @documents = @documents.order(sort_order(sort_column, sort_direction)).paginate(per_page: 10, page: params[:page]) if params[:all].blank?
      end
      format.odt { print }
    end
  end

  def autocomplete
    @documents = Document.order(:name).where('name ilike ?', "%#{params[:term]}%")
    render json: @documents.map(&:name)
  end

  def edit
    # authorize! :edit_document_place, @user if params[:user][:edit_document_place]
    @document = Document.find(params[:id])
    @document_directive = @document.document_directive.new # заготовка для новой связи с директивой
    @document_bproce = @document.bproce_document.new # заготовка для новой связи с процессом
  end

  def update
    flash[:notice] = 'Документ успешно обновлен.' if @document.update(document_params)
    respond_with(@document)
  end

  def update_file
    d_file = params[:document][:document_file] if params[:document].present?
    if d_file.present?
      flash[:notice] = 'Файл "' + d_file.original_filename + '" загружен.' if @document.update(document_file_params)
    else
      flash[:alert] = 'Ошибка - имя файла не указано.'
    end
    respond_with(@document)
  end

  def add_favorite
    @user_document = UserDocument.new(user_id: current_user.id, document_id: @document.id, link: 10)
    flash[:notice] = "##{@document.id} добавлен в Избранное." if @user_document.save
    @user_documents = UserDocument.where(document_id: @document.id).order('link, updated_at DESC').includes(:user).load # избранные документы пользователя
    # respond_with @document, notice: "##{@document.id} добавлен в Избранное."
    redirect_to @document
  end

  def add_to_favorite
    @user_document = UserDocument.new(document_id: @document.id, link: 1)
    # render :add_to_favorite
  end

  def update_favorite
    if params[:user_document].present?
      user_id = User.where(displayname: params[:user_document][:user]).first.id
      @user_document = UserDocument.new(user_id: user_id, document_id: @document.id, link: params[:user_document][:link])
      flash[:notice] = "##{@document.id} добавлен в Избранное для #{params[:user_document][:user]}." if @user_document.save
      @user_documents = UserDocument.where(document_id: @document.id).order('link, updated_at DESC').includes(:user).load # избранные документы пользователя
    end
    redirect_to @document
  end

  def show
    @user_document = UserDocument.where(user_id: current_user.id, document_id: @document.id).first if current_user
    @user_documents = UserDocument.where(document_id: @document.id).order('link, updated_at DESC').load if current_user
    respond_to do |format|
      format.html
      format.pdf { view }
      format.json { render json: @document }
      format.xml { render xml: @document }
    end
  end

  def bproce_create
    @document = Document.find(params[:id])
    @bproce_document = @document.bproce_document.new
    render :bproce_create
  end

  def show_files; end

  def new
    @document = Document.new(dlevel: 3, status: 'Проект', place: '?!') # место хранения не определено
    if params[:id].present? # будем добавлять документ процесса
      @bproce = Bproce.find(params[:id])
      @document.bproce_id = @bproce.id
    end
    @document.owner_id = current_user.id if current_user # владелец документа - пользователь
  end

  def clone
    document = Document.find(params[:id]) # документ - прототип
    @document = Document.new(status: 'Проект') # новый документ
    @document.name = document.name
    @document.description = document.description
    @document.dlevel = document.dlevel
    @document.approveorgan = document.approveorgan
    @document.note = 'создан из #' + document.id.to_s
    @document.owner_id = current_user.id if current_user # владелец документа - пользователь
    @document.place = '?!' # место хранения не определено
    if @document.save
      flash[:notice] = 'Successfully cloned Document.' if @document.save
      document.bproce_document.find_each do |bp| # клонируем ссылки на процессы
        bproce_document = BproceDocument.new(document_id: @document, bproce_id: bp)
        bproce_document.document = @document
        bproce_document.bproce = bp.bproce
        bproce_document.purpose = bp.purpose
        bproce_document.save
      end
      document.document_directive.find_each do |document_directive| # клонируем ссылки на директивы
        new_document_directive = DocumentDirective.new(document_id: @document.id, directive_id: document_directive.directive_id, note: document_directive.note)
        new_document_directive.save
      end
    end
  end

  def create
    @document = Document.new(document_params)
    @document.owner_id = current_user.id if current_user # владелец документа - пользователь
    if @document.save
      flash[:notice] = 'Документ создан'
      bproce = Bproce.find(@document.bproce_id) if @document.bproce_id # добавляем документ из процесса?
      if bproce
        bproce_document = BproceDocument.new(document_id: @document, bproce_id: bproce) # привязали документ к процессу
        bproce_document.document = @document
        bproce_document.bproce = bproce
        flash[:notice] = "Создан документ процесса ##{bproce.id}" if bproce_document.save
      end
      redirect_to document_path(@document)
    else
      render :new
    end
  end

  def destroy
    flash[:notice] = 'Документ удален' if @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url }
    end
  end

  def file_delete
    @document.document_file = nil
    flash[:notice] = 'Файл документа удален' if @document.save
    # render :show
    render :file_delete
  end

  def file_create
    render :file_create
  end

  def directive_create
    render :_form_directive
  end

  def approval_sheet
    approval_sheet_odt
  end

  private

  def document_params
    params.require(:document).permit(:name, :dlevel, :description, :owner_name, :status, :approveorgan, :approved, :note, :place, :file_delete, :bproce_id)
  end

  def document_file_params
    params.require(:document).permit(:document_file)
  end

  def user_document_params
    params.require(:user_document).permit(:document_id, :user_id, :link)
  end

  def print
    report = ODFReport::Report.new('reports/documents.odt') do |r|
      nn = 0 # порядковый номер документа
      nnp = 0
      first_part = 0 # номер раздела для сброса номера документа в разделе
      r.add_field 'REPORT_DATE', Date.today.strftime('%d.%m.%Y')
      # @title_doc = '' if !@title_doc

app/views/documents/_form.html.haml
= simple_form_for(@document) do |f|
  = f.error_notification
  = f.input :name, :as => :text
  = f.input :dlevel, :collection => 1..4, :as => :radio_buttons, :hint => 'Политики, Стратегии(1) - Положения, Описания(2) - Регламенты, Инструкции(3) - Свидетельства: Акты, Протоколы, Журналы(4)'
  = f.input :description
  = f.hidden_field :bproce_id
  = f.label 'Ответственный за документ'
  = f.autocomplete_field :owner_name, autocomplete_users_path
  
  -#= f.association :status_id, Category.all
  = f.input :status, :collection => %w[Утвержден Проект Согласование НеДействует], :prompt => 'Статус документа', :input_html => { :value => 'Утвержден'}
  = f.input :approveorgan, :collection => %w[ПредседательПравления Правление СоветДиректоров ОбщееСобрание], :prompt => 'Уполномоченный орган'
  -if @document.approved
    = f.input :approved, :as => :string, :input_html =>{:class=>'datepicker', :value => @document.approved.strftime("%d.%m.%Y")}
  -else
    = f.input :approved, :as => :string, :input_html =>{:class=>'datepicker'}
  = f.input :note

  -if can? :edit_document_place, Document
    = f.input :place, :hint => 'Место хранения оригиналов на бумаге (кратко: отдел папка)'
  -else
    - @document.place = '!?' if @document.place.blank?
    =  f.hidden_field :place
    Место хранения оригиналов на бумаге:
    %b= link_to @document.place, documents_path(place: @document.place), class: 'groups', title: DOCUMENT_PLACE.key(@document.place)

    %p
  -if can? :manage_tag, @document
    = f.input :tag_list, :label => 'Теги (через запятую)'
  = f.error :base
  
  -if can? :update, @document
    %p
    = f.button :submit

-#= @document_directives.inspect
-#= @document.directive
-#=@bproce.inspect

app/views/documents/_form_directive.html.haml
-if @document.id? # ну какие ссылки на директивы для нового документа
  %h3 Документ разработан на основании следующих директив:
  %table
    - @document.document_directive.each do |document_directive|
      %tr
      -if document_directive.id
        %td= link_to document_directive.directive.midname, directive_path(document_directive.directive)
        %td= document_directive.note
        -if can? :update, @document
          %td=link_to image_tag('action_stop.gif', :alt => 'Удалить'), document_directive, data: { confirm: document_directive.directive.midname + "\nДействительно хотите удалить ссылку на эту директиву?" }, :method => 'delete', class: 'button-img' if document_directive.directive

-if @document_directive
  = simple_form_for(@document_directive) do |dd|
    = dd.error_notification
    = dd.hidden_field :document_id
    = dd.hidden_field :directive_id
    = dd.label 'Директива'
    = dd.autocomplete_field :directive_number, autocomplete_directives_path, :id_elements => '#directive_id', :placeholder => 'номер директивы', :data => { :no_matches_label => '333' }
    = dd.input :note
    = dd.error :base
    %p
    -if can? :update, @document
      = dd.button :submit, 'Добавить Директиву'

app/views/documents/_show.html.haml
-title "Документ " + truncate(@document.name, length: 30)
-search 'Документ'
.id_
  \#
  = @document.id
%h2= @document.name
%h3 Описание:
= markdown(@document.description)
%h3
  -if @document.status
    ='"' + @document.status + '"'
  -if @document.approveorgan
    %b= @document.approveorgan
  -if @document.approved
    от
    %b= @document.approved.strftime('%d.%m.%Y')
%h3
  уровень документа:
  %b= link_to "#{@document.dlevel}: #{DOCUMENT_LEVEL.key(@document.dlevel)}", documents_path(dlevel: @document.dlevel.to_s), class: 'groups'

= render 'show_bproce_link'

%p
%h3
  Ответственный за документ:
  -if @document.owner_id?
    = link_to @document.owner_name, user_path(@document.owner_id)
  -else
    %b
    не задан

%h3 Примечание:
= raw add_link_from_id(@document.note, 'documents')

= render 'show_directive'

%p
%h3
  Место хранения оригинала:
  %b= link_to @document.place, documents_path(place: @document.place), class: 'groups', title: DOCUMENT_PLACE.key(@document.place) if !@document.place.blank?

#delete_file
  = render 'file_show'


- if can? :edit_document, @document
  #show_files
    = link_to 'Сохраненные файлы', show_files_document_path(@document), :remote => true   #, class: 'button'

%p
-if can? :view_document, @document
  #add_favorite
    -if @user_documents
      -if @user_documents.count > 0
        В Избранном:
        - @user_documents.each do |user_document|
          = link_to user_document.user.displayname, user_path(user_document.user_id, :anchor => 'Documents') if user_document.user
        %br
    -if @user_document && @user_document.document_id == @document.id
      = link_to 'Удалить из Избранного', user_document_path, :method => :delete if @user_document.link >= 10 # если документ не добавил менеджер по персоналу
    -else
      = link_to 'Добавить в Избранное', add_favorite_document_path(@document)
      = link_to 'Добавить в Обязательное', add_to_favorite_document_path(@document), :remote => true if current_user.role? :manager

%p
Теги документа:
= raw @document.tags.map { |t| link_to t, tag_documents_path(t.name), class: 'tags' }.join('&nbsp; ')

.info_
  -activity1 = PublicActivity::Activity.where(trackable_type: "Document", trackable_id: @document.id).order("created_at asc").first
  -if activity1
    = link_to 'создал', activities_path(type: "Document", id: @document.id)
    = activity1.updated_at.strftime('%d.%m.%Y %H:%M:%S')
    = activity1.owner.displayname.to_s
  -else
    создан
    = @document.created_at.strftime('%d.%m.%Y %H:%M:%S')
  %br
  -activity2 = PublicActivity::Activity.where(trackable_type: "Document", trackable_id: @document.id).order("created_at asc").last
  -if activity2
    = link_to 'изменил', activities_path(type: "Document", id: @document.id)
    = activity2.updated_at.strftime('%d.%m.%Y %H:%M:%S')
    = activity2.owner.displayname.to_s
  -else
    изменен
    = @document.updated_at.strftime('%d.%m.%Y %H:%M:%S')

%p
-if can? :update, @document
  = link_to 'Edit', edit_document_path(@document), :class => 'button'
= link_to 'Back', :back, :class => 'button'
-if @document.status
  -if @document.status == 'Проект' or @document.status == 'Согласование'
    = link_to 'Лист согласования', approval_sheet_document_path(@document), :class => 'button' if can? :update, Document
-if can? :clone, @document
  = link_to 'Clone', clone_document_path(@document), :class => 'button'
-if can? :destroy, @document
  = link_to 'Удалить', @document, data: { confirm: @document.name + "\nДействительно хотите удалить документ #" + @document.id.to_s + " ?" }, :method => 'delete', class: 'button'

app/views/documents/_show_bproce_link.html.haml
%p
- if @document.bproce_document.any? # есть ссылки из документа на другие процессы?
  %h3 
    Процесс:
    - @document.bproce_document.each do |bproce_document|
      = link_to bproce_document.bproce.name, bproce_path(bproce_document.bproce) + '/documents' # в документы процесса
      -if can? :update, Document
        = link_to '( ' + bproce_document.purpose.to_s + ' )', edit_bproce_document_path(bproce_document)
      -else
        = '( ' + bproce_document.purpose.to_s + ' )'

-else
  %h3 Процесс не назначен!
- if can? :update, @document || current_user && @document.owner_id == current_user.id # ответственный за документ тоже может добавлять процесс
  #update_bproce
    = link_to 'Добавить процесс', bproce_create_document_path(@document), remote: true

app/views/documents/index.html.haml
- search 'Документ'
- command_params = Hash.new
- command_search = Hash.new
- if @bproce
  - title "Документы процесса ##{@bproce.id}  #{@title_doc}"
  %h3
    Документы процесса
    = link_to @bproce.name, bproce_path(@bproce)
    = @title_doc
- elsif @directive
  - title "Документы директивы ##{@directive.id}"
  %h3
    Документы, разработанные на основании 
    = link_to @directive.shortname, directive_path(@directive)
- else
  - title 'Каталог Документов'
  %h2= @title_doc
  - if params[:search].present?
    - command_search = command_search.merge('search' => params[:search])
    - command_params = command_params.merge(command_search) # сохранить параметр для вызова Списка
  - command_params = command_params.merge('status' => params[:status]) if params[:status].present?
  - command_params = command_params.merge('place' => params[:place]) if params[:place].present?
  - command_params = command_params.merge('dlevel' => params[:dlevel]) if params[:dlevel].present?

%table
  %tr
    %th= sortable 'id', '#'
    %th= sortable 'name', 'Наименование'
    %th= sortable 'status', 'Статус'
    %th= sortable 'approved', 'От'
    %th Оригинал
    - if can? :update, Document
      %th
    - if can? :destroy, Document
      %th
    
  - @documents.each do |document|
    %tr
      %td
        .id_show_ ##{document.id}
      %td
        - if document.document_file_file_name # если есть файл документа, загруженный через paperclip
          -if can? :view_document, document
            - if File.exist?(document.pdf_path)
              = link_to image_tag('action_go.gif', alt: 'См.', title: 'Смотреть'), document.pdf_url, class: 'button-img'
        = link_to format_content(document.name), document_path(document)
        - if can? :manage_tag, document
          %sup= document.tag_list
      %td= document.status
      %td= document.approved.strftime('%d.%m.%Y') if document.approved
      %td= document.place 
      - if can? :update, document
        %td
          = link_to image_tag('page_edit.gif', alt: 'Изменить'), edit_document_path(document), class: 'button-img'
      - if can? :destroy, document
        %td
          - if !@directive
            - if !@bproce
              = link_to image_tag('action_stop.gif', alt: 'Удалить', title: 'Удалить' ), document, data: { confirm: document.name + "\nДействительно хотите удалить документ #" + document.id.to_s + " ?" }, method: 'delete', class: 'button-img'
            - else
              - bproce_document = document.bproce_document.where('bproce_id = ?', @bproce.id).first # ссылка на данный процесс из документа
              = link_to image_tag('action_stop.gif', alt: 'Удалить'),
                        bproce_document_path(bproce_document, bproce_id: @bproce.id),
                        data: { confirm: document.name + "\nДействительно хотите удалить ссылку из процесса ##{bproce_document.bproce_id} на этот документ?" },
                        method: 'delete',
                        class: 'button-img' if bproce_document
          - else # это документы Директивы, нельзя удалять сам документ - только ссылку из директивы
            - di = @directive.document_directive.where("directive_id = '?' and document_id = '?'", @directive.id, document.id).first
            = link_to image_tag('action_stop.gif', alt: 'Удалить'), di, data: { confirm: document.name + "\nДействительно хотите удалить ссылку из директивы на этот документ?" }, method: 'delete', class: 'button-img' if di

- unless params[:all].present?
  .apple_pagination
    = will_paginate @documents
%p
- if can? :create, Document
  = link_to 'Каталог', documents_path(command_params.merge(format: 'odt', all: '1')), class: 'button'
  - if @bproce
    = link_to 'Список', documents_path(format: 'odt', bproce_id: @bproce.id), class: 'button'
    = link_to 'Новый документ процесса', new_document_bproce_path(@bproce), class: 'button'
  - elsif @directive
    = link_to 'Список', documents_path(format: 'odt', directive_id: @directive.id), class: 'button'
    -# = link_to 'Новый документ директивы', new_document_directive_path(@directive), class: 'button'
  - else
    = link_to 'Список', documents_path(command_params.merge(format: 'odt')), class: 'button'
    = link_to 'Добавить новый документ', new_document_path, class: 'button'

%p
Статус:
- Document.select('status, count(id) as count').group(:status).order(:status).each do |d|
  - unless d.status.to_s.empty?
    - cl = (params[:status].present? && d.status == params[:status]) ? 'groups-s' : 'groups'
    - if @bproce
      = link_to d.status, bproce_path(@bproce) + "/documents?status=#{d.status}", class: cl
    - else
      = link_to d.status, documents_path(command_search.merge(status: d.status)), class: cl
    &nbsp;
%br
Уровень:
- Document.select('dlevel, count(id) as count').group(:dlevel).order(:dlevel).each do |d|
  - unless d.dlevel.to_s.empty?
    - cl = (params[:dlevel].present? && d.dlevel.to_s == params[:dlevel]) ? 'groups-s' : 'groups'
    = link_to DOCUMENT_LEVEL.key(d.dlevel), documents_path(dlevel: d.dlevel.to_s), class: cl, title: DOCUMENT_LEVEL.key(d.dlevel)
    &nbsp;
%br
Оригинал:
- Document.select('place, count(id) as count').group(:place).order(:place).each do |d|
  - unless d.place.to_s.empty?
    - cl = (params[:place].present? && d.place == params[:place]) ? 'groups-s' : 'groups'
    = link_to d.place, documents_path(command_search.merge(place: d.place.to_s)), class: cl, title: DOCUMENT_PLACE.key(d.place)
    &nbsp;
%p
Теги:
= raw Document.all_tags.map { |t| link_to t.name, tag_documents_path(t.name), class: 'tags' }.join('&nbsp; ')