config/routes.rb
Rails.application.routes.draw do
  resources :bproces, only: :autocomlete do
    get :autocomplete, on: :collection
  end
  resources :iresources, only: :autocomlete do
    get :autocomplete, on: :collection
  end
  resources :users, only: :autocomlete do
    get :autocomplete, on: :collection
  end
  resources :activities
  resources :agents do
    get :autocomplete, on: :collection
    member do
      get :new_contract # новый договор контрагента
    end
  end
  resources :bapps do
    get :autocomplete, on: :collection
  end
  resources :bproce_bapps, only: [:create, :destroy, :show, :edit, :update]
  resources :bproce_business_roles, only: [:show]
  resources :bproce_iresources, only: [:new, :create, :destroy, :show, :edit, :update]
  resources :bproce_workplaces, only: [:create, :destroy, :show]
  resources :bproce_contracts, except: :index
  resources :bproce_documents, except: :index
  resources :bproces, except: :new do
    resources :bapps
    resources :business_roles, only: [:new]
    resources :documents, only: [:new, :index]
    resources :contracts, only: [:index]
    collection do
      get :manage
      post :rebuild
      get :list
    end
    member do
      get :order  # распоряжение о назначении исполнителей в процесс
      get :doc    # описание процесса
      get :card   # карточка процесса
      get :check_list # чек-лист карточки процесса
      get :check_list_improve # чеклист улучшения процесса
      get :metrics # метрики процесса
      get :new_metric # добавить новую метрику в процесс
      get :new_document, to: 'documents#new'
      get :new_sub_process # добавить подпроцесс
    end
  end
  resources :business_roles do
    member do
      get :create_user # назначить исполнителя
      post :update_user
      get :mail # отправить всем исполнителям письмо
      post :mail_all
    end
  end
  resources :contracts do
    get :autocomplete, on: :collection
    member do
      get :approval_sheet # Лист согласования
      get :scan_create
      get :scan_delete
      post :update_scan
      get :bproce_create
      get :clone # создать похожий договор
    end
  end
  resources :contract_scans, only: [:destroy, :edit, :update]
  resources :directives do
    resources :documents  # документы на основании директивы
    get :autocomplete, on: :collection
    member do
      get :document_create
      post :document_update
    end
  end
  resources :documents do
    get :autocomplete, on: :collection
    member do
      get :file_create
      get :file_delete
      patch :update_file
      get :approval_sheet # Лист согласования
      get :clone # создать карточку похожего документа
      get :add_favorite     # добровольное занесение в избранное
      get :add_to_favorite  # юрист заносит в обязательные
      post :update_favorite
      get :show_files
      get :bproce_create
    end
  end
  resources :document_directives
  resources :iresources

  resources :home, only: [:index] do
    member do
      get :create_letter    # создать официальное письмо
      get :create_memo      # создать служебную записку
      get :create_vacation  # создать заявление на отпуск
    end
  end

  resources :letters do     # письма, корреспонденция
    collection do
      get :senders
      get :log_week    # журнал регистрации за неделю
      get :check       # контроль
    end
    member do
      get :appendix_create
      get :appendix_delete
      post :appendix_update
      get :clone            # письмо от того же корреспондента
      get :create_outgoing  # исходящее письмо на входящее
      get :create_requirement # создать требование
      get :create_task
      get :create_user # назначить исполнителя
      post :update_user
      get :register       # зарегистрировать
      get :reestr         # реестр выписок
    end
  end
  resources :letter_appendixes, only: [:destroy, :edit, :update]

  resources :metrics do
    member do
      get :values
      get :new_value
      get :set
      get :test
      get :set_values
    end
  end
  resources :metric_values, only: [:edit, :update, :new, :create, :destroy]
  get 'bproces/tags/:tag', to: 'bproces#index', as: :tag_bproces
  get 'bapps/tags/:tag', to: 'bapps#index', as: :tag_bapps
  get 'documents/tags/:tag', to: 'documents#index', as: :tag_documents
  # get 'tags/:tag', to: 'bproces#index', as: :tag
  # get 'tags', to: 'bproces#index'

  resources :tasks do
    collection do
      get :check       # контроль
    end
    member do
      get :create_user      # назначить исполнителя
      post :update_user
      get :report
    end
  end
  resources :terms
  resources :requirements do
    member do
      get :create_task
      get :create_user      # назначить исполнителя
      post :update_user
      get :tasks_list
      get :tasks_report
    end
  end
  resources :roles, only: [:index, :show]

  devise_for :users
  devise_scope :users do
    get 'sign_in',  to: 'devise/sessions#new'
    get 'sign_out', to: 'devise/sessions#destroy'
    get 'sign_up',  to: 'devise/registrations#new'
  end
  resources :users, only: [:index, :show, :edit, :update] do
    member do
      get :order # распоряжение о назначении исполнителя на роли в процессах
      get :pass # пропуск
      get :uworkplaces
      get :uroles
      get :documents
      get :contracts
      get :contracts_pay
      get :resources
      get :processes
      get :execute # К исполнению (письма, задачи, требования).
      get :avatar_create
      get :avatar_delete
      patch :update_avatar
      get :move_to    # назначить другого пользователя всех бизнес-ролей сотрудника
      post :business_roles_move_to  # перенести бизнес-роли новому пользователю
      get :stop_all # прератить исполнение всех ролей сотрудником
    end
    resources :roles, only: [:create, :destroy]
  end
  resources :user_business_roles, only: [:new, :create, :destroy, :edit, :update, :show]
  resources :user_documents, only: [:destroy]
  resources :user_letters, only: [:destroy, :update, :create, :show]
  resources :user_requirements, only: [:destroy, :update, :create, :show]
  resources :user_tasks, only: [:destroy, :update, :create, :show]
  resources :user_workplaces

  # match '/bproceses' => 'bproces#list', :via => :get  # получение полного списка процессов
  match '/bprocess' => 'bproces#manage', :via => :get # получение полного списка процессов
  # match '/bproces/:id/card' => 'bproces#card', :via => :get  # карточка процесса
  # match '/bproces/:id/doc' => 'bproces#doc', :via => :get  # заготовка описания процесса
  match '/workplaces/switch' => 'workplaces#switch', :via => :get # подключения рабочих мест
  resources :workplaces do
    get :autocomplete, on: :collection
    member do
      get :create_user # назначить исполнителя
      post :update_user
    end
  end

  match '/about' => 'pages#about', via: :get
  get 'pages/about'
  root to: 'home#index'
end

app/controllers/letters_controller.rb
# frozen_string_literal: true

class LettersController < ApplicationController
  respond_to :html, :json
  before_action :authenticate_user!, only: %i[edit new create update destroy register show]
  before_action :set_letter, only: %i[show edit update destroy register reestr]
  helper_method :sort_column, :sort_direction
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found
  # rubocop:disable Metrics/LineLength
  def index
    @title_letter = 'Письма '
    if params[:user].present?
      user = User.find(params[:user])
      @letters = Letter.joins(:user_letter).where('user_letters.user_id = ?', params[:user])
      @title_letter += "исполнителя [ #{user.displayname} ]"
      if params[:status].present?
        @letters = @letters.status(params[:status])
        @title_letter += "в статусе [ #{LETTER_STATUS.key(params[:status].to_i)} ]"
      else
        @letters = @letters.where('letters.status < 90', params[:status])
        @title_letter += ' не завершенные'
      end
    elsif params[:date].present? # письма за дату
      @letters = Letter.where(date: params[:date])
      @title_letter += 'за ' + params[:date]
    elsif params[:regdate].present? # письма за дату регистрации
      @letters = Letter.where(regdate: params[:regdate])
      @title_letter += 'зарегистрированные ' + params[:regdate]
    elsif params[:addresse].present? # письма от адресанта + письма адресату
      @letters = Letter.where('sender ILIKE ?', params[:addresse].strip)
      @title_letter += 'адреса[н]та ' + params[:addresse]
    elsif params[:status].present?
      @letters = Letter.status(params[:status])
      @title_letter += "в статусе [ #{LETTER_STATUS.key(params[:status].to_i)} ]"
    elsif params[:search].present?
      @letters = Letter.search(params[:search]).includes(:user_letter, :letter_appendix)
    else
      @letters = Letter.search(params[:search]).where('status < 90').includes(:user_letter, :letter_appendix)
      @title_letter += 'не завершенные'
    end
    if params[:search].blank?
      if params[:out].present?
        @letters = @letters.where('in_out <> 1')
        @title_letter += ' Исходящие'
      else
        @letters = @letters.where('in_out = 1')
        @title_letter += ' Входящие'
      end
    end
    @letters = @letters.order(sort_order(sort_column, sort_direction)).paginate(per_page: 10, page: params[:page])
  end

  def show
    @letter_link = Letter.find(@letter.letter_id) if @letter.letter_id
    @letters_outgoing = Letter.where(letter_id: @letter.id).order('date DESC') # исходящие из данного письма
    @requirements = Requirement.where(letter_id: @letter.id) # требования, созданные из письма
    @tasks = Task.where(letter_id: @letter.id) # задачи, созданные из письма
    respond_to do |format|
      format.html
      format.json { render json: @letter }
    end
  end

  def new
    @letter = Letter.new(in_out: 1, status: 0)
    @letter.sender = params[:addresse] if params[:addresse].present?
    @letter.author_id = current_user.id if user_signed_in?
    @letter.duedate = (Time.current + 10.days).strftime('%d.%m.%Y') # срок исполнения - даем 10 дней по умолчанию
  end

  def edit
    @user_letter = UserLetter.new(letter_id: @letter.id) # заготовка для ответственного
    # если автора нет - назначим первого, кто внес изменения
    @letter.author_id = current_user.id if @letter.author_id.blank? && user_signed_in?
  end

  def create
    @letter = Letter.new(letter_params)
    if @letter.save
      redirect_to @letter, notice: 'Письмо создано.'
    else
      render action: 'new'
    end
  end

  def update
    status_was = @letter.status # старые значения
    if @letter.update(letter_params)
      @letter.result += "\r\n" + Time.current.strftime('%d.%m.%Y %H:%M:%S') + ": #{current_user.displayname} - " + params[:letter][:action] if params[:letter][:action].present?
      if @letter.status >= 90 && status_was < 90 # стало завершено
        @letter.result += "\r\n" + Time.current.strftime('%d.%m.%Y %H:%M:%S') + ": #{current_user.displayname} считает, что все работы по письму исполнены"
      elsif @letter.status < 90 && status_was >= 90 # стало не завершено, а было завершено
        @letter.result += "\r\n" + Time.current.strftime('%d.%m.%Y %H:%M:%S') + ": #{current_user.displayname} считает, что работы по письму надо продолжить"
      end
      if params[:letter][:action].present? || (status_was != @letter.status)
        @letter.update_column(:result, @letter.result.to_s)
        @letter.update_column(:status, 10) if @letter.status < 10 # на исполнении, если Назначено или Новое
      end
      redirect_to @letter, notice: 'Письмо сохранено.'
    else
      @user_letter = UserLetter.new(letter_id: @letter.id)
      render action: 'edit'
    end
  end

  def destroy
    @letter.destroy
    redirect_to letters_url, notice: 'Письмо удалено.'
  end

  def check
    @letters = Letter.where('status < 90 and duedate <= ?', Date.current + 1).order(:duedate)
    check_report
  end

  def clone
    letter = Letter.find(params[:id]) # письмо - прототип
    @letter = Letter.new(sender: letter.sender, in_out: letter.in_out, status: 0)
    @letter.author_id = current_user.id if user_signed_in?
    @letter.duedate = (Time.current + 10.days).strftime('%d.%m.%Y') # срок исполнения - даем 10 дней по умолчанию
    @letter.source = letter.source
    @letter.subject = letter.subject
  end

  def create_outgoing
    letter = Letter.find(params[:id]) # входящее письмо
    @letter = Letter.new(sender: letter.sender, in_out: 2, letter_id: letter.id, status: 10,
                         date: Time.current.strftime('%d.%m.%Y'), number: 'б/н')
    @letter.author_id = current_user.id if user_signed_in?
    @letter.duedate = (Time.current + 3.days).strftime('%d.%m.%Y') # срок исполнения - даем 3 дней по умолчанию
    @letter.source = letter.source
    @letter.subject = letter.subject
    @letter.result = "это ответ на #{letter.name} (##{letter.id})"
  end

  def create_requirement
    letter = Letter.find(params[:id]) # письмо - прототип
    @requirement = Requirement.new(letter_id: letter.id, author_id: current_user.id)
    # redirect_to requirements_new(@requirement) and return
    redirect_to(new_requirement_url(letter_id: letter.id)) && return
  end

  def create_task
    parent_letter = Letter.find(params[:id])
    redirect_to(new_task_url(letter_id: parent_letter.id)) && return
  end

  def create_user
    @letter = Letter.find(params[:id])
    @user_letter = UserLetter.new(letter_id: @letter.id) # заготовка для ответственного
    render :create_user
    # #respond_with(@letter)
  end

  def update_user
    user_letter = UserLetter.new(user_letter_params) if params[:user_letter].present?
    if user_letter
      user_letter_clone = UserLetter.where(letter_id: user_letter.letter_id, user_id: user_letter.user_id).first # проверим - нет такого исполнителя?
      if user_letter_clone
        user_letter_clone.status = user_letter.status
        user_letter = user_letter_clone
      end
      if user_letter.save
        flash[:notice] = "Исполнитель #{user_letter.user_name} назначен"
        begin
          UserLetterMailer.user_letter_create(user_letter, current_user).deliver_now # оповестим нового исполнителя
        rescue Net::SMTPAuthenticationError, Net::SMTPServerBusy, Net::SMTPSyntaxError, Net::SMTPFatalError, Net::SMTPUnknownError => e
          flash[:alert] = "Error sending mail to #{user_letter.user.email}"
        end
        @letter = user_letter.letter # Letter.find(@user_letter.letter_id)
        @letter.update_column(:status, 5) if @letter.status < 1 # если есть ответственные - статус = Назначено
      end
    else
      flash[:alert] = 'Ошибка - ФИО Исполнителя не указано.'
    end
    respond_with(@letter)
  end

  def appendix_create
    @letter = Letter.find(params[:id])
    @letter_appendix = LetterAppendix.new(letter_id: @letter.id)
    render :appendix_create
  end

  def appendix_update
    @letter_appendix = LetterAppendix.new(letter_appendix_params) if params[:letter_appendix].present?
    if @letter_appendix
      @letter = @letter_appendix.letter
      flash[:notice] = 'Файл приложения "' + @letter_appendix.appendix_file_name + '" загружен.' if @letter_appendix.save
    else
      flash[:alert] = 'Ошибка - имя файла не указано.'
    end
    respond_with(@letter_appendix.letter)
  end

  # реестр регистрации
  def log_week
    d = if params[:week_day].present?
          params[:week_day].to_date
        else
          Date.current - 7 # по умолчанию - предыдущая неделя
        end
    week_start = d - d.days_to_week_start # начало недели отчета
    week_end = week_start + 6 # конец недели отчета
    @log_period = "с #{week_start.strftime('%d.%m.%Y')} по #{week_end.strftime('%d.%m.%Y')}"
    @week_number = week_start.strftime('%Y-%m-%d').to_s
    @letters = Letter.where('regdate > ? and regdate < ?', week_start - 1, week_end + 1).order(:regnumber)
    if params[:out].present?
      @letters = @letters.where('in_out <> 1')
      @in_out = 2
    else
      @letters = @letters.where('in_out = 1')
      @in_out = 1
    end
    if @letters.any?
      log_week_report
    else
      redirect_to letters_path, alert: "Нет зарегистрированных писем за период: #{week_start.strftime('%d.%m.%Y')} - #{week_end.strftime('%d.%m.%Y')}."
    end
  end

  # реестр
  def reestr
    @letters = Letter.where('sender ILIKE ? and regdate = ?', @letter.sender, @letter.regdate).order(:regnumber)
    @sender = @letter.sender
    reestr_report
  end

  def register
    len_regnumber = Letter.where('in_out = ? and regdate > ?', @letter.in_out, Time.current.beginning_of_year).maximum('length(regnumber)') # длина строки наибольшего номера
    max_reg_number = Letter.where('in_out = ? and regdate > ? and length(regnumber) >= ?', @letter.in_out, Time.current.beginning_of_year, len_regnumber).maximum(:regnumber).to_i
    max_reg_number += 1 # next registration number for current year and directiom

app/views/letters/_appendix_create.html.haml
= simple_form_for @letter_appendix, url: appendix_update_letter_path, html: { multipart: true } do |f|
  = f.error_notification
  = f.hidden_field :letter_id
  = f.input :name
  = f.input :appendix, hint: 'Выберите файл для загрузки'

  = f.error :base
  - if true or can? :update, @letter
    %p
    = f.button :submit, 'Сохранить файл'

app/views/letters/_appendixes.html.haml
- if @letter.id? # ну какие ссылки на сканы для нового письма
  - if @letter.letter_appendix.count > 0
    %h3 Приложения:
    - @letter.letter_appendix.each do |letter_appendix|
      - if can? :update, letter_appendix
        = link_to letter_appendix.name, edit_letter_appendix_path(letter_appendix)
      - else
        = letter_appendix.name
        ("#{letter_appendix.appendix_file_name}": #{letter_appendix.appendix_updated_at.strftime('%d.%m.%Y %H:%M:%S')} #{letter_appendix.appendix_file_size})

      - if true or can? :update, letter_appendix
        = link_to image_tag('action_stop.gif', alt: 'Удалить'),
          letter_appendix,
          data: { confirm: 'Файл "' + letter_appendix.appendix_file_name  + '": ' + letter_appendix.appendix_updated_at.strftime('%d.%m.%Y %H:%M:%S') + "\nДействительно хотите удалить его \nиз письма #{letter_appendix.letter.name} ?" },
          method: 'delete',
          class: 'button-img'
      %br

app/views/letters/_create_user.html.haml
= simple_form_for @user_letter, :url => update_user_letter_path, :html => { :multipart => true } do |f|
  = f.error_notification
  = f.hidden_field :letter_id
  = f.label 'Исполнитель'
  = f.autocomplete_field :user_name, autocomplete_users_path
  = f.input :status, as: :boolean
  = f.error :base
  = f.button :submit, 'Добавить Исполнителя'

app/views/letters/_form_appendixes.html.haml
- if @letter.id? # ну какие ссылки на сканы для нового договора
  - if @letter.letter_appendix.count > 0
    %h3 Файлы (сканы):
    - @letter.letter_appendix.each do |letter_appendix|
      - if can? :update, letter_appendix
        = link_to letter_appendix.name, edit_letter_appendix_path(letter_appendix)
      - else
        = letter_appendix.name
      = ' ("' + letter_appendix.scan_file_name + '": ' + letter_appendix.scan_updated_at.strftime('%d.%m.%Y %H:%M:%S') + ' ' + letter_appendix.scan_file_size.to_s + ")"
      - if can? :update, letter_appendix
        = link_to image_tag('action_stop.gif', alt: 'Удалить'), letter_appendix, data: { confirm: 'Файл "' + letter_appendix.scan_file_name  + '": ' + letter_appendix.scan_updated_at.strftime('%d.%m.%Y %H:%M:%S') + "\nДействительно хотите удалить из письма ##{letter_appendix.letter.id} ?" }, method: 'delete', class: 'button-img'
      %br

app/views/letters/_letters_outgoing.html.haml
%h4 Письма, созданные на основании данного письма:
%table
  - @letters_outgoing.each do |letter|
    %tr
      %td ##{letter.id}
      %td
        - regnumber = (letter.in_out == 1 ? 'Вх.' : 'Исх.')
        - regnumber += "№ #{letter.regnumber}"
        - regnumber += " от #{letter.regdate.strftime('%d.%m.%y')}" if letter.regdate
        = link_to link_to image_tag('out_mail.png', size: "16x16") + regnumber, letter
      %td= letter.subject
      %td
        - if letter.duedate
          - if letter.status < 90 and letter.duedate <= Date.current
            %span{ style: "color: red;" }
              = letter.duedate.strftime("%d.%m.%y")
          - else
            = letter.duedate.strftime("%d.%m.%y")
          - if letter.completion_date
            - if letter.completion_date > letter.duedate
              %br
                %span{ style: "color: red;" }
                  = letter.completion_date.strftime("%d.%m.%y")
      %td= LETTER_STATUS.key(letter.status)
      %td
        - i = 0
        - letter.user_letter.includes(:user).each do |user_letter|
          - if user_letter.user
            - if i > 0
              %br
            - s = "#{user_letter.user.displayname}"
            - s += "\u2713".html_safe if user_letter.status and user_letter.status > 0   # пометим ответственного
            -# = link_to s, letters_path(user: user_letter.user)
            = link_to s, user_path(user_letter.user)
          - else
            удалить ссылку
            = user_letter.inspect
          - i += 1

app/views/letters/appendix_create.js.erb
$("#appendix_update").html("<%= escape_javascript( render(:partial => "appendix_create") ) %>");

app/views/letters/show.html.haml
- title "Письмо № #{@letter.number} от #{@letter.date.strftime('%d.%m.%Y')}"
- search 'Письмо'
%table
  %tr
    %td
      - if @letter.in_out != 1 # Исходящее
        .image_inline_right
          =image_tag 'out_mail.png', size: "64x64", alt: "#{LETTER_DIRECTION.key(@letter.in_out)}"
      - else
        .image_inline_left
          =image_tag 'in_mail.png', size: "64x64", alt: "#{LETTER_DIRECTION.key(@letter.in_out)}"
      .large
        - if @letter.in_out != 1 # Исходящее
          - if @letter.regnumber.blank?
            - if can? :registr, @letter
              %h2
                = link_to 'Зарегистрировать', register_letter_path(@letter), class: 'button'
          - else
            Исх.№
            %b #{@letter.regnumber}
            - if @letter.regdate
              от
              %b
                = link_to @letter.regdate.strftime('%d.%m.%Y'), letters_path(regdate: @letter.regdate.strftime('%d.%m.%Y'))
        %br
        - if @letter_link
          ответ на
          = link_to "Вх.№ #{@letter_link.number}", letter_path(@letter_link)
          от #{@letter_link.date.strftime('%d.%m.%Y')}
        - elsif !@letter.number.blank? && @letter.number != 'б/н' && @letter.number != '-'
          Исх.№ #{@letter.number} от
          = link_to @letter.date.strftime('%d.%m.%Y'), letters_path(date: @letter.date.strftime('%d.%m.%Y')) if @letter.date

        - if @letter.in_out == 1 # Входящее
          - if @letter.regnumber.blank?
            - if can? :registr, @letter
              %h2
                = link_to 'Зарегистрировать', register_letter_path(@letter), class: 'button'
          - else
            %br
              Зарегистрирован:
              = @letter.in_out == 1 ? 'Вх.№' : 'Исх.№'
              %b #{@letter.regnumber}
              - if @letter.regdate
                от
                %b
                  = link_to @letter.regdate.strftime('%d.%m.%Y'), letters_path(regdate: @letter.regdate.strftime('%d.%m.%Y'))
    %td
      .id_ ##{@letter.id}
      .large
        - if @letter.in_out == 1
          Отправитель:
        - else
          Получатель:
      %h2= link_to @letter.sender, letters_path(addresse: @letter.sender)

  %tr
    %td
      %h3
        %b [ #{@letter.subject} ]
    %td
      \&nbsp;
  %tr
    %td
      %h3 Краткое содержание (о чем):
      = simple_format(@letter.body, {}, {})
    %td
      %h3 Источник: #{@letter.source}
%h3
  Срок исполнения:
  - if @letter.duedate
    %b= @letter.duedate.strftime('%d.%m.%Y')
    - if @letter.status < 90
      - days = @letter.duedate - Date.current
      = " (осталось #{days.to_i} дн.)" if days > 0
      - if days <= 0
        %span{ style: 'color: red;' }
          = " (опоздание #{(-days).to_i} дн.)" if days < 0
          = " сегодня!" if days == 0
  - if @letter.completion_date
    [ фактически:
    %b= @letter.completion_date.strftime('%d.%m.%Y')

    - if @letter.status >= 90
      - days = 0
      - days = @letter.completion_date - @letter.duedate if @letter.duedate
      - if days > 0
        %span{ style: 'color: red;' }
          (опоздание #{days.to_i} дн.)
    ]

- @letter.letter_appendix.each do |letter_appendix|
  .floating-box
    - if File.exist?(letter_appendix.appendix.path) # есть исходный файл документа
      - appendix_name = "#{letter_appendix.name}:" unless letter_appendix.name
      = link_to image_tag('action_go.gif', alt: 'См.', title: 'Смотреть') + "#{appendix_name} #{letter_appendix.appendix_file_name}", letter_appendix.appendix.url
    - else
      #{letter_appendix.appendix_file_name}
    %br (#{letter_appendix.appendix_updated_at.strftime('%d.%m.%Y %H:%M:%S')}  #{letter_appendix.appendix_file_size})
- if can? :update, @letter
  #appendix_update.floating-box
    = link_to 'Добавить файл приложения', appendix_create_letter_path(@letter), remote: true

%hr
%h3
  - if @letter.author_id?
    Автор:
    = link_to @letter.author.displayname, user_path(@letter.author.id)
    &nbsp; &nbsp;
  Исполнители:
  - is_can_update = can? :update, @letter
  - is_can_update = true if @letter.author && @letter.author.id == current_user.id # автор может добавлять других исполнителей
  - @letter.user_letter.each do |user_letter|
    = link_to user_letter.user.displayname, letters_path(user: user_letter.user)
    &nbsp;
    - if user_letter.status && user_letter.status > 0
      \- отв.
    &nbsp;
    - is_can_update = true if user_letter.user.id == current_user.id # исполнители могут добавлять других исполнителей

- if is_can_update # автор и исполнители могут добавлять других исполнителей
  #create_user
    = link_to 'Добавить Исполнителя', create_user_letter_path(@letter), remote: true

%h3
  Статус:
  %b= LETTER_STATUS.key(@letter.status)
%h3 Результат исполнения:
= simple_format(@letter.result, {}, {})

%hr
= render 'letters_outgoing' if @letters_outgoing.any?
- if @requirements.any?
  %h4 Созданы Требования:
  - @requirements.each do |requirement|
    = link_to "Требование [#{requirement.label}]", requirement
    от #{requirement.date.strftime('%d.%m.%Y')}
    %br
= render 'tasks' if @tasks.any?

.info_
  - activity1 = PublicActivity::Activity.where(trackable_type: 'Letter', trackable_id: @letter.id).order('created_at asc').first
  - if activity1
    = link_to 'создал', activities_path(type: 'Letter', id: @letter.id)
    = activity1.updated_at.strftime('%d.%m.%Y %H:%M:%S')
    = activity1.owner.displayname.to_s
  - else
    создан
    = @letter.created_at.strftime('%d.%m.%Y %H:%M:%S')
  %br
  - activity2 = PublicActivity::Activity.where(trackable_type: 'Letter', trackable_id: @letter.id).order('created_at asc').last
  - if activity2
    = link_to 'изменил', activities_path(type: 'Letter', id: @letter.id)
    = activity2.updated_at.strftime('%d.%m.%Y %H:%M:%S')
    = activity2.owner.displayname.to_s
  - else
    изменен
    = @letter.updated_at.strftime('%d.%m.%Y %H:%M:%S')
%p
- if @letter.in_out == 1
  = link_to 'Back', letters_path, class: 'button'
- else
  = link_to 'Back', letters_path(out: 1), class: 'button'

- if is_can_update # автор и исполнители могут изменять письмо
  = link_to 'Edit', edit_letter_path(@letter), class: 'button'
  - if can? :create_outgoing, @letter
    = link_to 'Новое похожее', clone_letter_path(@letter), class: 'button'
    = link_to 'Создать Исходящее', create_outgoing_letter_path(@letter), class: 'button' if @letter.in_out == 1
  = link_to '+Задачу', create_task_letter_path(@letter), class: 'button'
  = link_to '+Требование', create_requirement_letter_path(@letter), class: 'button'
  - if can? :create_outgoing, @letter
    = link_to 'Реестр выписок', reestr_letter_path(@letter), class: 'button'